/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "on-primary-fixed-variant": "#004c6e",
        "primary-fixed-dim": "#89ceff",
        "on-primary-container": "#003751",
        "tertiary-fixed-dim": "#c3c7cb",
        "secondary-fixed": "#d3e4fe",
        "surface-variant": "#dae2fd",
        "surface-tint": "#006591",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        tertiary: "#5a5f62",
        "inverse-surface": "#283044",
        "surface-container": "#eaedff",
        "on-primary-fixed": "#001e2f",
        "on-secondary-container": "#54647a",
        background: "#faf8ff",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "outline-variant": "#bec8d2",
        "on-tertiary-fixed": "#171c1f",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed-variant": "#43474b",
        "tertiary-container": "#979ca0",
        "on-secondary-fixed": "#0b1c30",
        "secondary-container": "#d0e1fb",
        "on-background": "#131b2e",
        "inverse-primary": "#89ceff",
        primary: "#006591",
        "on-tertiary-container": "#2f3437",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "on-surface-variant": "#3e4850",
        "on-surface": "#131b2e",
        secondary: "#505f76",
        "surface-dim": "#d2d9f4",
        surface: "#faf8ff",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#38485d",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "surface-container-high": "#e2e7ff",
        "tertiary-fixed": "#dfe3e7",
        "primary-container": "#0ea5e9",
        outline: "#6e7881",
        "primary-fixed": "#c9e6ff",
        "on-secondary": "#ffffff",
        // dark helpers
        "dark-base": "#020617",
        "dark-elevated": "#0f172a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "container-max-width": "1440px",
        "base-unit": "4px",
        "margin-desktop": "40px",
        "margin-tablet": "24px",
        "stack-lg": "32px",
        "stack-md": "16px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        display: ["Plus Jakarta Sans", "Inter", "system-ui", "sans-serif"],
      },
      boxShadow: {
        ambient: "0 8px 30px rgb(0 0 0 / 0.04)",
        card: "0 4px 16px rgba(15, 23, 42, 0.08)",
      },
      maxWidth: {
        container: "1440px",
      },
    },
  },
  plugins: [],
};
