#!/usr/bin/env bash
# Generate file env siap deploy (Portainer / Dokploy / docker compose).
#
# Usage:
#   ./scripts/generate-stack-env.sh https://sintesa.sekolah.sch.id
#   ./scripts/generate-stack-env.sh   # akan diminta input domain

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/.env"
DOMAIN="${1:-}"

if [[ -z "$DOMAIN" ]]; then
  read -r -p "PUBLIC_URL (contoh: https://sintesa.sekolah.sch.id): " DOMAIN
fi

DOMAIN="${DOMAIN%/}"

if [[ -z "$DOMAIN" ]]; then
  echo "PUBLIC_URL wajib diisi." >&2
  exit 1
fi

rand() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 "$1" | tr -d '/+=' | head -c "$1"
  else
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"
  fi
}

JWT_SECRET="$(rand 48)"
POSTGRES_PASSWORD="$(rand 32)"

SCHEME="${DOMAIN%%://*}"
COOKIE_SECURE="true"
if [[ "$SCHEME" == "http" ]]; then
  COOKIE_SECURE="false"
fi

cat >"$OUT" <<EOF
# Generated by scripts/generate-stack-env.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Deploy guide: deploy-to-docker.md

PUBLIC_URL=${DOMAIN}
JWT_SECRET=${JWT_SECRET}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

POSTGRES_USER=sintesa
POSTGRES_DB=sintesa
HTTP_PORT=8080

COOKIE_SECURE=${COOKIE_SECURE}
COOKIE_SAMESITE=lax
CORS_ORIGINS=${DOMAIN}

RUN_DB_SEED=true

SINTESA_IMAGE_TAG=latest

SSO_BASE_URL=https://sso-v2.smage.my.id
SSO_CLIENT_ID=
SSO_CLIENT_SECRET=
SSO_REDIRECT_URI=${DOMAIN}/api/auth/sso/callback
SSO_JWT_SECRET=
SSO_API_KEY=
EOF

echo "✓ Env ditulis ke: $OUT"
echo ""
echo "Langkah berikutnya:"
echo "  1) Isi SSO_CLIENT_ID, SSO_CLIENT_SECRET, SSO_JWT_SECRET di $OUT"
echo "  2) Daftarkan callback SSO: ${DOMAIN}/api/auth/sso/callback"
echo "  3) docker compose up -d"
echo "  4) Set RUN_DB_SEED=false setelah deploy pertama berhasil"